server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true

server:
  port: 8080


---
spring:
  config:
    activate:
      on-profile: prod
## mudar data source
